### ISSUE TITLE
empty feature file

### ISSUE THREAD

**Issue by jdevoo** [mdsol/skyfire#9]
Hello, I tried a basic run using Eclipse Luna and UMLDesigner. At the moment, the generated feature file turns out empty.

```
INFO  | CucumberTestGenerator | CucumberTestGenerator:generateCucumberScenario:392 | Read the specified UML model from my.uml
INFO  | AbstractTestGenerator | AbstractTestGenerator:getTestPaths:81 | Generate abstract test paths from a flat graph
INFO  | AbstractTestGenerator | AbstractTestGenerator:getTestPaths:103 | Edge coverage is used. The number of total edges is 4
INFO  | AbstractTestGenerator | AbstractTestGenerator:getTestPaths:104 | The test requirements of edges are: [[1,2], [2,3], [1,4], [4,3]]
size :2
INFO  | AbstractTestGenerator | AbstractTestGenerator:getTestPaths:110 | 2 test paths are generated to satisfy edge coverage. The total nodes is 6
INFO  | CucumberTestGenerator | CucumberTestGenerator:generateCucumberScenario:406 | Generate abstract test paths on the flattened graph
INFO  | CucumberTestGenerator | CucumberTestGenerator:generateTests:525 | Generate abstract tests
INFO  | CucumberTestGenerator | CucumberTestGenerator:generateCucumberScenario:421 | Create Cucumber feature file which is located at .\bla

```

Java code below

```
public class App
{
    public static void main( String[] args ) throws IOException, InvalidInputException, InvalidGraphException
    {
        List<com.mdsol.skyfire.Test> tests = new ArrayList<Test>();
        CucumberTestGenerator generator = new CucumberTestGenerator(tests);
        EPackage.Registry.INSTANCE.put("http://www.eclipse.org/uml2/5.0.0/UML", UMLPackage.eINSTANCE);
        Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put(UMLResource.FILE_EXTENSION, UMLResource.Factory.INSTANCE);
        generator.generateCucumberScenario(Paths.get("my.uml"), TestCoverageCriteria.EDGECOVERAGE, "some feature description", Paths.get("./bla"));
    }
}

```

Finally, the feature file comes out like this

```
Feature: some feature description

Scenario:



Scenario:




```

![capture](https://cloud.githubusercontent.com/assets/16983/18143902/6a9a3d92-6fc4-11e6-995e-5c2ee0be54d2.JPG)

**Comment by jdevoo** [comment]
Looks like an incompatible XMI type between skyfire's registered ones and UMLDesigner 5.0.
I removed the registration in my code above which is not needed but no success loading the .uml file with UMLDesigner. 

[EDIT]
Solution was to pull latest org.eclipse.uml2.uml, org.eclipse.uml2.types and org.eclipse.uml2.common from acceleo repos as per <repositories> tag - they have more recent versions which are compatible with UMLDesigner 5.0/Luna 4.4
The tests have to be skipped as the models are based on older profiles (and I couldn't figure out the right way to load several of them)

**Comment by nli-mdsol** [comment]
@jdevoo Skyfire doesn't support UML 5.0.0 now. When I started developing Skyfire, I used UML libraries that supported 4.0.0. I didn't have time to upgrade Skyfire to support UML 5.0.0. 
There is one compromise: downgrading your UML diagram to 4.0.0. In a UML file, on the second line, there should be something like "xmlns:uml="http://www.eclipse.org/uml2/4.0.0/UML." 
If yours is 5.0.0, you just need to manually change it to 4.0.0. It should work.
If you have more development information for UML 5.0.0, such as APIs, please let me know. I may find time to make Skyfire work for 5.0.0.
